apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-jkins-sa-rl-bn
  namespace: learnjkc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-jkins-sa-rl
subjects:
- kind: ServiceAccount
  name: k8s-jkins-sa
